name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: docker build image
      run: |
        DOCKER_BUILDKIT=1 docker build -t py_docker .

    - name: Publish Docker Image
      run: |
        docker push $DOCKER_USERNAME/adarshbabbula:latest
        docker system prune -f -a
